FROM node:22-alpine3.18

RUN npm install -g @angular/cli@17.3.7

RUN apk add --update --no-cache \
    git \
    lazygit \
    neovim \
    ripgrep \
    alpine-sdk

RUN git clone https://github.com/LazyVim/starter ~/.config/nvim

LABEL authors="angie"

WORKDIR /usr/src/app

EXPOSE 4200